# This file is part of the NuCms package.
# (c) Jacek Bednarek

nucms_admin_locale:
    type: sylius.resource
    resource: |
        alias: nucms.locale
        section: admin
        templates: NugatoNuCmsBundle:Admin/Crud
        grid: nucms_admin_locale
        redirect: update
