# This file is part of the NuCms package.
# (c) Jacek Bednarek

nucms_api_page:
    type: sylius.resource_api
    resource: |
        alias: nucms.page
        section: api
        serialization_version: 1

nucms_api_locale:
    type: sylius.resource_api
    resource: |
        alias: nucms.locale
        section: api
        serialization_version: 1
