# This file is part of the NuCms package.
# (c) Jacek Bednarek

sylius_resource:
    resources:
        nucms.page:
            driver: doctrine/orm
            classes:
                model: Nugato\Bundle\NuCmsBundle\Entity\Page
                form: Nugato\Bundle\NuCmsBundle\Form\PageType
            translation:
                classes:
                    model: Nugato\Bundle\NuCmsBundle\Entity\PageTranslation
                    form: Nugato\Bundle\NuCmsBundle\Form\PageTranslationType
